from pynput.keyboard import Key, Controller
import time
from keyboard import press

key = Controller()


halt = time.sleep(.3)
time.sleep(5)

slash = key.press('/')
halt = time.sleep(.3)
key.type('One.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)



slash = key.press('/')
halt = time.sleep(.3)
key.type('Two.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Three.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Four.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Five.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Six.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Seven.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Eight.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Nine.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Ten.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Eleven.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)
 

slash = key.press('/')
halt = time.sleep(.3)
key.type('Twelve.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirteen.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Fourteen.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Fifteen.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Sixteen.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type("Seventeen.")
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Eighteen.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Nineteen.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty One.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty Two.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty Three.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty Four.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty Five.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty Six.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
key.type('Twenty Seven.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty Eight.')
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Twenty Nine.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')


slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty One.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
key.type('Thirty Two.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty Three.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty Four.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty Five.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty Six.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)


slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty Seven.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty Eight.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.2)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Thirty Nine.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
halt = time.sleep(.3)

slash = key.press('/')
halt = time.sleep(.3)
key.type('Forty.')
halt = time.sleep(.3)
press('enter')
halt = time.sleep(.3)
press('space')
press('enter')

